add_test([=[DisplayIntegrationTest.CheckpointStartup]=]  /app/build_tests_local/display_integration_test [==[--gtest_filter=DisplayIntegrationTest.CheckpointStartup]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DisplayIntegrationTest.CheckpointStartup]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DisplayIntegrationTest.CheckpointFinal]=]  /app/build_tests_local/display_integration_test [==[--gtest_filter=DisplayIntegrationTest.CheckpointFinal]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DisplayIntegrationTest.CheckpointFinal]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DisplayIntegrationTest.CheckpointButtonFeedback]=]  /app/build_tests_local/display_integration_test [==[--gtest_filter=DisplayIntegrationTest.CheckpointButtonFeedback]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DisplayIntegrationTest.CheckpointButtonFeedback]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DisplayIntegrationTest.CheckpointChart]=]  /app/build_tests_local/display_integration_test [==[--gtest_filter=DisplayIntegrationTest.CheckpointChart]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DisplayIntegrationTest.CheckpointChart]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DisplayIntegrationTest.CheckpointYAxisStability]=]  /app/build_tests_local/display_integration_test [==[--gtest_filter=DisplayIntegrationTest.CheckpointYAxisStability]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DisplayIntegrationTest.CheckpointYAxisStability]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  display_integration_test_TESTS DisplayIntegrationTest.CheckpointStartup DisplayIntegrationTest.CheckpointFinal DisplayIntegrationTest.CheckpointButtonFeedback DisplayIntegrationTest.CheckpointChart DisplayIntegrationTest.CheckpointYAxisStability)
