add_test([=[CoreLibTest.SensorMockInitializes]=]  /app/build_tests_local/emulator_test [==[--gtest_filter=CoreLibTest.SensorMockInitializes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CoreLibTest.SensorMockInitializes]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CoreLibTest.InteractionTransitions]=]  /app/build_tests_local/emulator_test [==[--gtest_filter=CoreLibTest.InteractionTransitions]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CoreLibTest.InteractionTransitions]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CoreLibTest.HandleNaNValues]=]  /app/build_tests_local/emulator_test [==[--gtest_filter=CoreLibTest.HandleNaNValues]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CoreLibTest.HandleNaNValues]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CoreLibTest.AppSetupExecutes]=]  /app/build_tests_local/emulator_test [==[--gtest_filter=CoreLibTest.AppSetupExecutes]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CoreLibTest.AppSetupExecutes]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  emulator_test_TESTS CoreLibTest.SensorMockInitializes CoreLibTest.InteractionTransitions CoreLibTest.HandleNaNValues CoreLibTest.AppSetupExecutes)
