add_test([=[GUITest.GetFontSizeAboveFont24]=]  /app/build_tests_local/gui_test [==[--gtest_filter=GUITest.GetFontSizeAboveFont24]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GUITest.GetFontSizeAboveFont24]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GUITest.GetFontSizeExactFont24]=]  /app/build_tests_local/gui_test [==[--gtest_filter=GUITest.GetFontSizeExactFont24]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GUITest.GetFontSizeExactFont24]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GUITest.GetFontSizeFont20Range]=]  /app/build_tests_local/gui_test [==[--gtest_filter=GUITest.GetFontSizeFont20Range]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GUITest.GetFontSizeFont20Range]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GUITest.GetFontSizeExactFont20]=]  /app/build_tests_local/gui_test [==[--gtest_filter=GUITest.GetFontSizeExactFont20]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GUITest.GetFontSizeExactFont20]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GUITest.GetFontSizeFont16Range]=]  /app/build_tests_local/gui_test [==[--gtest_filter=GUITest.GetFontSizeFont16Range]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GUITest.GetFontSizeFont16Range]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GUITest.GetFontSizeExactFont16]=]  /app/build_tests_local/gui_test [==[--gtest_filter=GUITest.GetFontSizeExactFont16]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GUITest.GetFontSizeExactFont16]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GUITest.GetFontSizeFont12Range]=]  /app/build_tests_local/gui_test [==[--gtest_filter=GUITest.GetFontSizeFont12Range]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GUITest.GetFontSizeFont12Range]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GUITest.GetFontSizeExactFont12]=]  /app/build_tests_local/gui_test [==[--gtest_filter=GUITest.GetFontSizeExactFont12]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GUITest.GetFontSizeExactFont12]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GUITest.GetFontSizeFont8Range]=]  /app/build_tests_local/gui_test [==[--gtest_filter=GUITest.GetFontSizeFont8Range]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GUITest.GetFontSizeFont8Range]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GUITest.GetFontSizeExactFont8]=]  /app/build_tests_local/gui_test [==[--gtest_filter=GUITest.GetFontSizeExactFont8]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GUITest.GetFontSizeExactFont8]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GUITest.GetFontSizeTooSmall]=]  /app/build_tests_local/gui_test [==[--gtest_filter=GUITest.GetFontSizeTooSmall]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GUITest.GetFontSizeTooSmall]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GUITest.GetFontSizeMismatched]=]  /app/build_tests_local/gui_test [==[--gtest_filter=GUITest.GetFontSizeMismatched]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GUITest.GetFontSizeMismatched]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[GUITest.GetFontSizeBestFit]=]  /app/build_tests_local/gui_test [==[--gtest_filter=GUITest.GetFontSizeBestFit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[GUITest.GetFontSizeBestFit]=]  PROPERTIES WORKING_DIRECTORY /app/build_tests_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  gui_test_TESTS GUITest.GetFontSizeAboveFont24 GUITest.GetFontSizeExactFont24 GUITest.GetFontSizeFont20Range GUITest.GetFontSizeExactFont20 GUITest.GetFontSizeFont16Range GUITest.GetFontSizeExactFont16 GUITest.GetFontSizeFont12Range GUITest.GetFontSizeExactFont12 GUITest.GetFontSizeFont8Range GUITest.GetFontSizeExactFont8 GUITest.GetFontSizeTooSmall GUITest.GetFontSizeMismatched GUITest.GetFontSizeBestFit)
